package com.historiaclinica.hospital;
// Generated 10-abr-2013 14:38:16 by Hibernate Tools 3.2.1.GA



/**
 * Especializacion generated by hbm2java
 */
public class Especializacion  implements java.io.Serializable {


     private Integer id;
     private String nombre;

    public Especializacion() {
    }

    public Especializacion(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


