package com.historiaclinica.hospital;
// Generated 10-abr-2013 14:38:16 by Hibernate Tools 3.2.1.GA



/**
 * Medico generated by hbm2java
 */
public class Medico  implements java.io.Serializable {


     private Integer id;
     private int idPersona;
     private int idEspecializacion;

    public Medico() {
    }

    public Medico(int idPersona, int idEspecializacion) {
       this.idPersona = idPersona;
       this.idEspecializacion = idEspecializacion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public int getIdEspecializacion() {
        return this.idEspecializacion;
    }
    
    public void setIdEspecializacion(int idEspecializacion) {
        this.idEspecializacion = idEspecializacion;
    }




}


