package com.historiaclinica.hospital;
// Generated 10-abr-2013 14:38:16 by Hibernate Tools 3.2.1.GA



/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private Integer id;
     private int idPersona;
     private int idHistoriaClinica;

    public Paciente() {
    }

    public Paciente(int idPersona, int idHistoriaClinica) {
       this.idPersona = idPersona;
       this.idHistoriaClinica = idHistoriaClinica;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public int getIdHistoriaClinica() {
        return this.idHistoriaClinica;
    }
    
    public void setIdHistoriaClinica(int idHistoriaClinica) {
        this.idHistoriaClinica = idHistoriaClinica;
    }




}


