package com.historiaclinica.hospital;
// Generated 10-abr-2013 14:38:16 by Hibernate Tools 3.2.1.GA



/**
 * Parametro generated by hbm2java
 */
public class Parametro  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     private int idClase;

    public Parametro() {
    }

    public Parametro(String descripcion, int idClase) {
       this.descripcion = descripcion;
       this.idClase = idClase;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getIdClase() {
        return this.idClase;
    }
    
    public void setIdClase(int idClase) {
        this.idClase = idClase;
    }




}


