package com.historiaclinica.hospital;
// Generated 10-abr-2013 14:38:16 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer id;
     private int tipoDocumento;
     private long nroDocumento;
     private String nombres;
     private String apellidos;
     private String email;
     private Date fechaNacimiento;
     private String telefono;
     private String direccion;
     private int idUsurio;

    public Persona() {
    }

	
    public Persona(int tipoDocumento, long nroDocumento, String nombres, String apellidos, Date fechaNacimiento, int idUsurio) {
        this.tipoDocumento = tipoDocumento;
        this.nroDocumento = nroDocumento;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.fechaNacimiento = fechaNacimiento;
        this.idUsurio = idUsurio;
    }
    public Persona(int tipoDocumento, long nroDocumento, String nombres, String apellidos, String email, Date fechaNacimiento, String telefono, String direccion, int idUsurio) {
       this.tipoDocumento = tipoDocumento;
       this.nroDocumento = nroDocumento;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.email = email;
       this.fechaNacimiento = fechaNacimiento;
       this.telefono = telefono;
       this.direccion = direccion;
       this.idUsurio = idUsurio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(int tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public long getNroDocumento() {
        return this.nroDocumento;
    }
    
    public void setNroDocumento(long nroDocumento) {
        this.nroDocumento = nroDocumento;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getIdUsurio() {
        return this.idUsurio;
    }
    
    public void setIdUsurio(int idUsurio) {
        this.idUsurio = idUsurio;
    }




}


