package com.modelo;
// Generated 13-may-2013 15:44:06 by Hibernate Tools 3.2.1.GA



/**
 * PermisosxusurioId generated by hbm2java
 */
public class PermisosxusurioId  implements java.io.Serializable {


     private int idusurio;
     private int idpermiso;

    public PermisosxusurioId() {
    }

    public PermisosxusurioId(int idusurio, int idpermiso) {
       this.idusurio = idusurio;
       this.idpermiso = idpermiso;
    }
   
    public int getIdusurio() {
        return this.idusurio;
    }
    
    public void setIdusurio(int idusurio) {
        this.idusurio = idusurio;
    }
    public int getIdpermiso() {
        return this.idpermiso;
    }
    
    public void setIdpermiso(int idpermiso) {
        this.idpermiso = idpermiso;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PermisosxusurioId) ) return false;
		 PermisosxusurioId castOther = ( PermisosxusurioId ) other; 
         
		 return (this.getIdusurio()==castOther.getIdusurio())
 && (this.getIdpermiso()==castOther.getIdpermiso());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdusurio();
         result = 37 * result + this.getIdpermiso();
         return result;
   }   


}


