package com.modelo;
// Generated 30-abr-2013 12:33:26 by Hibernate Tools 3.2.1.GA


import com.entidades.TipoPersona;
import java.util.Date;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int id;
     private int tipodocumento;
     private long nrodocumento;
     private String nombres;
     private String apellidos;
     private String email;
     private Date fechanacimiento;
     private String telefono;
     private String direccion;
     private int idusurio;
     private TipoPersona tipo;

    public Persona() {
    }

	
    public Persona(int id, int tipodocumento, long nrodocumento, String nombres, String apellidos, Date fechanacimiento, int idusurio) {
        this.id = id;
        this.tipodocumento = tipodocumento;
        this.nrodocumento = nrodocumento;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.fechanacimiento = fechanacimiento;
        this.idusurio = idusurio;
    }
    public Persona(int id, int tipodocumento, long nrodocumento, String nombres, String apellidos, String email, Date fechanacimiento, String telefono, String direccion, int idusurio) {
       this.id = id;
       this.tipodocumento = tipodocumento;
       this.nrodocumento = nrodocumento;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.email = email;
       this.fechanacimiento = fechanacimiento;
       this.telefono = telefono;
       this.direccion = direccion;
       this.idusurio = idusurio;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getTipodocumento() {
        return this.tipodocumento;
    }
    
    public void setTipodocumento(int tipodocumento) {
        this.tipodocumento = tipodocumento;
    }
    public long getNrodocumento() {
        return this.nrodocumento;
    }
    
    public void setNrodocumento(long nrodocumento) {
        this.nrodocumento = nrodocumento;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getIdusurio() {
        return this.idusurio;
    }
    
    public void setIdusurio(int idusurio) {
        this.idusurio = idusurio;
    }
    
    public TipoPersona getTipoPersona(){
        return tipo;
    }




}


