package com.modelo;
// Generated 30-abr-2013 12:33:26 by Hibernate Tools 3.2.1.GA



/**
 * Historiaclinica generated by hbm2java
 */
public class Historiaclinica  implements java.io.Serializable {


     private int id;
     private Integer estado;

    public Historiaclinica() {
    }

	
    public Historiaclinica(int id) {
        this.id = id;
    }
    public Historiaclinica(int id, Integer estado) {
       this.id = id;
       this.estado = estado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }




}


