package com.modelo;
// Generated 13-may-2013 15:44:06 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Cita generated by hbm2java
 */
public class Cita  implements java.io.Serializable {


     private int id;
     private Date fechahora;
     private int idpaciente;
     private int idmedico;

    public Cita() {
    }

	
    public Cita(int id, int idpaciente, int idmedico) {
        this.id = id;
        this.idpaciente = idpaciente;
        this.idmedico = idmedico;
    }
    public Cita(int id, Date fechahora, int idpaciente, int idmedico) {
       this.id = id;
       this.fechahora = fechahora;
       this.idpaciente = idpaciente;
       this.idmedico = idmedico;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getFechahora() {
        return this.fechahora;
    }
    
    public void setFechahora(Date fechahora) {
        this.fechahora = fechahora;
    }
    public int getIdpaciente() {
        return this.idpaciente;
    }
    
    public void setIdpaciente(int idpaciente) {
        this.idpaciente = idpaciente;
    }
    public int getIdmedico() {
        return this.idmedico;
    }
    
    public void setIdmedico(int idmedico) {
        this.idmedico = idmedico;
    }




}


