package com.modelo;
// Generated 13-may-2013 15:44:06 by Hibernate Tools 3.2.1.GA



/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private int id;
     private int idpersona;
     private int idhistoriaclinica;

    public Paciente() {
    }

    public Paciente(int id, int idpersona, int idhistoriaclinica) {
       this.id = id;
       this.idpersona = idpersona;
       this.idhistoriaclinica = idhistoriaclinica;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(int idpersona) {
        this.idpersona = idpersona;
    }
    public int getIdhistoriaclinica() {
        return this.idhistoriaclinica;
    }
    
    public void setIdhistoriaclinica(int idhistoriaclinica) {
        this.idhistoriaclinica = idhistoriaclinica;
    }




}


