package com.modelo;
// Generated 13-may-2013 15:44:06 by Hibernate Tools 3.2.1.GA



/**
 * Permisosxusurio generated by hbm2java
 */
public class Permisosxusurio  implements java.io.Serializable {


     private PermisosxusurioId id;

    public Permisosxusurio() {
    }

    public Permisosxusurio(PermisosxusurioId id) {
       this.id = id;
    }
   
    public PermisosxusurioId getId() {
        return this.id;
    }
    
    public void setId(PermisosxusurioId id) {
        this.id = id;
    }




}


