package com.historiaclinica.hospital;
// Generated 10-abr-2013 14:38:16 by Hibernate Tools 3.2.1.GA



/**
 * Historiaclinica generated by hbm2java
 */
public class Historiaclinica  implements java.io.Serializable {


     private Integer id;
     private Integer estado;

    public Historiaclinica() {
    }

    public Historiaclinica(Integer estado) {
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }




}


